version: '3.8'

services:
  # User Management Service
  usermanagement:
    image: shehabwaleed/gp_auth_service:latest
    hostname: "userManagementService"
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=${user_management_CONNECTION_STRING}

  usermanagementH2:
    image: shehabwaleed/gp_auth_service:latest
    hostname: "userManagementServiceH2"
    ports:
      - "8082:8080"
    environment:
      - ConnectionStrings__DefaultConnection=${user_management_h2_CONNECTION_STRING}
      - Kafka__BootstrapServers=${user_management_h2_KAFKA_BROKERS}


  # Patient Profile Service
  patientProfile:
    image: shehabwaleed/gp_patient_profile_service:latest
    hostname: "patientProfileService"
    ports:
      - "8081:8080"
    environment:
      - ConnectionStrings__DefaultConnection=${patient_profile_CONNECTION_STRING}

  patientProfileH2:
    image: shehabwaleed/gp_patient_profile_service:latest
    hostname: "patientProfileServiceH2"
    ports:
      - "8083:8080"
    environment:
      - ConnectionStrings__DefaultConnection=${patient_profile_h2_CONNECTION_STRING}
      - Kafka__BootstrapServers=${patient_profile_h2_KAFKA_BROKERS}


  # Staff Management Service
  staffManagement:
    image: shehabwaleed/gp_staff_management:latest
    hostname: "staffManagementService"
    ports:
      - "8090:80"
    environment:
      APP_NAME: "Staff Management Service"
      DB_CONNECTION: ${staff_management_DB_CONNECTION}
      DB_HOST: ${staff_management_DB_HOST}
      DB_PORT: ${staff_management_DB_PORT}
      DB_DATABASE: ${staff_management_DB_DATABASE}
      DB_USERNAME: ${staff_management_DB_USERNAME}
      DB_PASSWORD: ${staff_management_DB_PASSWORD}
      APP_URL: ${staff_management_APP_URL}
      JWT_SECRET: ${JWT_SECRET}
      KAFKA_BROKERS: ${staff_management_KAFKA_BROKERS}

  staffManagementH2:
    image: shehabwaleed/gp_staff_management:latest
    hostname: "staffManagementServiceH2"
    ports:
      - "8092:80"
    environment:
      APP_NAME: "Staff Management Service H2"
      DB_CONNECTION: ${staff_management_h2_DB_CONNECTION}
      DB_HOST: ${staff_management_h2_DB_HOST}
      DB_PORT: ${staff_management_h2_DB_PORT}
      DB_DATABASE: ${staff_management_h2_DB_DATABASE}
      DB_USERNAME: ${staff_management_h2_DB_USERNAME}
      DB_PASSWORD: ${staff_management_h2_DB_PASSWORD}
      APP_URL: ${staff_management_h2_APP_URL}
      JWT_SECRET: ${JWT_SECRET_h2}
      KAFKA_BROKERS: ${staff_management_h2_KAFKA_BROKERS}

  # Booking Service
  booking:
    image: shehabwaleed/gp_booking_service:latest
    hostname: "bookingService"
    ports:
      - "8091:80"
    environment:
      APP_NAME: "Booking Service"
      DB_CONNECTION: ${booking_DB_CONNECTION}
      DB_HOST: ${booking_DB_HOST}
      DB_PORT: ${booking_DB_PORT}
      DB_DATABASE: ${booking_DB_DATABASE}
      DB_USERNAME: ${booking_DB_USERNAME}
      DB_PASSWORD: ${booking_DB_PASSWORD}
      APP_URL: ${booking_APP_URL}
      JWT_SECRET: ${JWT_SECRET}
      KAFKA_BROKERS: ${booking_KAFKA_BROKERS}

  bookingH2:
    image: shehabwaleed/gp_booking_service:latest
    hostname: "bookingServiceH2"
    ports:
      - "8093:80"
    environment:
      APP_NAME: "Booking Service H2"
      DB_CONNECTION: ${booking_h2_DB_CONNECTION}
      DB_HOST: ${booking_h2_DB_HOST}
      DB_PORT: ${booking_h2_DB_PORT}
      DB_DATABASE: ${booking_h2_DB_DATABASE}
      DB_USERNAME: ${booking_h2_DB_USERNAME}
      DB_PASSWORD: ${booking_h2_DB_PASSWORD}
      APP_URL: ${booking_h2_APP_URL}
      JWT_SECRET: ${JWT_SECRET_h2}
      KAFKA_BROKERS: ${booking_h2_KAFKA_BROKERS}

  ehr:
    image: shehabwaleed/ehr_service:latest
    hostname: "ehrService"
    ports:
      - "8085:8080"
    environment:
      - ConnectionStrings__DefaultConnection=${ehr_CONNECTION_STRING}  

  ehrAuth:
    image: shehabwaleed/gp_ehr_auth_service:latest
    hostname: "ehrAuthService"
    ports:
      - "8086:8080"
    environment:
      - ConnectionStrings__DefaultConnection=${ehr_auth_CONNECTION_STRING}  

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: --cleanup --interval 5

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "9090:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=hospital-one
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=${SERVER_IP}:9093
      - KAFKA_CLUSTERS_0_ZOOKEEPER=${SERVER_IP}:2181
    restart: unless-stopped

  kafka-ui-h2:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui-h2
    ports:
      - "9091:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=hospital-two
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=${SERVER_IP}:9095
      - KAFKA_CLUSTERS_0_ZOOKEEPER=${SERVER_IP}:2182
    restart: unless-stopped