version: '3.8'

services:
  usermanagement:
    image: shehabwaleed/gp_auth_service:latest
    hostname: "userManagementService"
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=${user_management_CONNECTION_STRING}

  staffManagement:
    image: shehabwaleed/gp_staff_management:latest
    hostname: "staffManagementService"
    ports:
      - "8090:80"
    environment:
      DB_CONNECTION: ${staff_management_DB_CONNECTION}
      DB_HOST: ${staff_management_DB_HOST}
      DB_PORT: ${staff_management_DB_PORT}
      DB_DATABASE: ${staff_management_DB_DATABASE}
      DB_USERNAME: ${staff_management_DB_USERNAME}
      DB_PASSWORD: ${staff_management_DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - kafka-network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:SASL_PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://${SERVER_IP}:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_PLAIN_USERNAME: ${KAFKA_SASL_PLAIN_USERNAME}
      KAFKA_SASL_PLAIN_PASSWORD: ${KAFKA_SASL_PLAIN_PASSWORD}
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"
      KAFKA_SUPER_USERS: User:admin
    ports:
      - "9092:9092"
    networks:
      - kafka-network

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: --cleanup --interval 5

networks:
  kafka-network:
    driver: bridge