version: '3.8'

services:
  usermanagement:
    image: shehabwaleed/gp_auth_service:latest
    hostname: "userManagementService"
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=${user_management_CONNECTION_STRING}

  patientProfile:
    image: shehabwaleed/gp_patient_profile_service:latest
    hostname: "patientProfileService"
    ports:
      - "8081:8080"
    environment:
      - ConnectionStrings__DefaultConnection=${patient_profile_CONNECTION_STRING}

  staffManagement:
    image: shehabwaleed/gp_staff_management:latest
    hostname: "staffManagementService"
    ports:
      - "8090:80"
    environment:
      APP_NAME: "Staff Management Service"
      DB_CONNECTION: ${staff_management_DB_CONNECTION}
      DB_HOST: ${staff_management_DB_HOST}
      DB_PORT: ${staff_management_DB_PORT}
      DB_DATABASE: ${staff_management_DB_DATABASE}
      DB_USERNAME: ${staff_management_DB_USERNAME}
      DB_PASSWORD: ${staff_management_DB_PASSWORD}
      APP_URL: ${staff_management_APP_URL}
      JWT_SECRET: ${JWT_SECRET}

  booking:
    image: shehabwaleed/gp_booking_service:latest
    hostname: "bookingService"
    ports:
      - "8091:80"
    environment:
      APP_NAME: "Booking Service"
      DB_CONNECTION: ${booking_DB_CONNECTION}
      DB_HOST: ${booking_DB_HOST}
      DB_PORT: ${booking_DB_PORT}
      DB_DATABASE: ${booking_DB_DATABASE}
      DB_USERNAME: ${booking_DB_USERNAME}
      DB_PASSWORD: ${booking_DB_PASSWORD}
      APP_URL: ${booking_APP_URL}
      JWT_SECRET: ${JWT_SECRET}

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: --cleanup --interval 5
