name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Write SSH private key to the file
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Generate env file
        run: |
          cat <<EOL > .env
          # Staff management service
          staff_management_DB_CONNECTION=${{ secrets.staff_management_DB_CONNECTION }}
          staff_management_DB_HOST=${{ secrets.staff_management_DB_HOST }}
          staff_management_DB_PORT=${{ secrets.staff_management_DB_PORT }}
          staff_management_DB_DATABASE=${{ secrets.staff_management_DB_DATABASE }}
          staff_management_DB_USERNAME=${{ secrets.staff_management_DB_USERNAME }}
          staff_management_DB_PASSWORD=${{ secrets.staff_management_DB_PASSWORD }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          
          # User management service
          user_management_CONNECTION_STRING=${{ secrets.user_management_CONNECTION_STRING }}

          # Kafka
          KAFKA_SASL_PLAIN_USERNAME=${{ secrets.KAFKA_SASL_PLAIN_USERNAME }}
          KAFKA_SASL_PLAIN_PASSWORD=${{ secrets.KAFKA_SASL_PLAIN_PASSWORD }}

          # Global
          SERVER_IP=${{ secrets.SERVER_IP }}
          EOL

      - name: Deploy to the server
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avzr --exclude=.git
          path: ./
          remote_path: ${{ secrets.REMOTE_PATH }}
          remote_host: ${{ secrets.SERVER_IP }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Update containers
        run: |
          ssh -v -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.REMOTE_USER }}@${{ secrets.SERVER_IP }} "cd ${{ secrets.REMOTE_PATH }} && docker-compose down --rmi all && docker compose up -d"
